Drop PostgreSQL 9.6 support
The code can still work with it, but the way extensions SQL scripts are
defined to install an extension has changed in a way that make annoying
to keep SQL installer for version 9.6 and before.

It raised as I was testing a new version and GHA was failling on 9.6 and
before with message similar to:

```
CREATE EXTENSION pgfincore;

ERROR:  could not stat file "/usr/share/postgresql/9.6/pgfincore/pgfincore--2.0.0.sql": No such file or directory
```

After PostgreSQL 10, engine is smarter to find "install paths" from
"upgrade paths"...

See for example:

```
SELECT * FROM pg_extension_update_paths('pgfincore') where source < target order by 1,2 ;
 source | target |         path
--------+--------+----------------------
 1.2    | 1.3.1  | 1.2--1.3.1
 1.2    | 1.4    | 1.2--1.3.1--1.4
 1.2    | 1.5    | 1.2--1.3.1--1.4--1.5
 1.3.1  | 1.4    | 1.3.1--1.4
 1.3.1  | 1.5    | 1.3.1--1.4--1.5
 1.4    | 1.5    | 1.4--1.5
```